//
// Copyright (c) 2021-2022 - Yupiik SAS - https://www.yupiik.com
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

= Yupiik Logging

See link:https://yupiik.github.io/yupiik-logging/.

== Build

Build is just about running `mvn package` on the project.

Minisite build/publish commands are in the root pom.xml (`mvn clean yupiik-tools:minisite@doc`).

A small trick can be needed to run the integration test depending your local setup.
If you have write permission issues with docker do the following:

. cp integration-test/projects/jul /tmp
. cd /tmp/jul
. sed 's/project\.version/<yupiik logging current version>/' pom.xml
. mvn package

It will download in the local m2 repository graalvm and test dependencies.
Since we mount it in the test docker image it will avoid downloads during the test and therefore permission issues.

TIP: you can need to run the integration test arthur command before being able to build the whole project since it relies on the presence of the distribution if docker container can't write to your local maven repository.
